swagger: '2.0'
info:
  description: API que contém os recurosos para o e-Commerce Compra Fácil / Equipe 9.
  version: '1.0.0'
  title: Compra Fácil API
  termsOfService: https://github.com/eNove/unicamp-engsoft-2020-inf332-pratica2
  contact:
    email: comprafacil@enove.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost
basePath: /precos/v1
tags:
  - name: promocoes
security:
  - client_id: []
  - access_token: []
securityDefinitions:
  client_id:
    type: apiKey
    in: header
    name: client_id
  access_token:
    type: apiKey
    in: header
    name: access_token
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /promocoes:
    get:
      tags:
        - promocoes
      summary: Obtém promoções
      description: Obtém produtos em promoção no momento.
      parameters:
      - name: categoria
        in: query
        type: string
        description: Categoria do produto
        required: false
      - name: valormaximo
        in: query
        type: number
        description: Maior preço promocional aceitável.
        required: false 
      - name: produtos
        in: query
        type: array
        items:
          type: string
        description: Categoria do produto.
        required: false
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: array
            items:
              $ref: '#/definitions/produto_promocao'
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
  /{idfornecedor}/promocoes:
    post:
      tags:
        - promocoes
      summary: Cadastra promoções
      description: Obtém produtos em promocao no momento.
      parameters:
      - name: "idfornecedor"
        in: "path"
        description: "Id do fornecedor na plataforma"
        required: true
        type: "integer"
        format: "int64"
      - in: body
        name: body
        description: Promoções de produtos do fornecedor.
        required: true
        schema:
          $ref: '#/definitions/promocao'
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: boolean
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
    put:
      tags:
        - promocoes
      summary: atuliza promoções
      description: Obtém produtos em promocao no momento.
      parameters:
      - name: "idfornecedor"
        in: "path"
        description: "Id do fornecedor na plataforma"
        required: true
        type: "integer"
        format: "int64"
      - in: body
        name: body
        description: Promoções de produtos do fornecedor.
        required: true
        schema:
          $ref: '#/definitions/promocao'
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: boolean
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
    get:
      tags:
        - promocoes
      summary: Obtem promoções de um fornecedor especifico
      description: Obtém produtos em promocao no momento de um fornecedor especifico.
      parameters:
      - name: "idfornecedor"
        in: "path"
        description: "Id do fornecedor na plataforma"
        required: true
        type: "integer"
        format: "int64"
      - name: categoria
        in: query
        type: string
        description: Categoria do produto
        required: false
      - name: valormaximo
        in: query
        type: number
        description: Maior preço promocional aceitável.
        required: false 
      - name: produtos
        in: query
        type: array
        items:
          type: string
        description: Categoria do produto.
        required: false
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: array
            items:
              $ref: '#/definitions/produto_promocao'
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
    delete:
      tags:
        - promocoes
      summary: Cancela a promocao de um produto pelo nome
      parameters:
      - name: "idfornecedor"
        in: "path"
        description: "Id do fornecedor na plataforma"
        required: true
        type: "integer"
        format: "int64"
      - name: "nome_produto"
        in: body
        schema:
          $ref: '#/definitions/produto_deleta_promocao'
      responses:
        '200':
          description: Sucesso.
          schema:
            type: boolean
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
  /{idfornecedor}/promocoes/{categoria}:
    delete:
      tags:
        - promocoes
      summary: Cancela todas as promocoes de uma categoria de produtos.
      parameters:
      - name: "idfornecedor"
        in: "path"
        description: "Id do fornecedor na plataforma"
        required: true
        type: "integer"
        format: "int64"
      - name: "categoria"
        in: "path"
        description: "Categoria do produto"
        required: true
        type: "string"
      responses:
        '200':
          description: Sucesso.
          schema:
            type: boolean
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
definitions:
  promocao:
    type: object
    properties:
      idfornecedor:
        type: string
      produtos:
        type: array
        items:
          $ref: '#/definitions/produto-promocao-cadastro'
  produto-promocao-cadastro:
    type: object
    properties:
      nome_produto:
        type: string
        description: Nome do produto.
      categoria:
        type: string
        description: Categoria do produto na plataforma.
      preco_promocional: 
        type: number
        description: Preço promocional do produto.
      data_inicio_promocao:
        type: string
        format: date-time
      data_fim_promocao:
        type: string
        format: date-time
  produto_promocao:
    type: object
    properties:
      idproduto:
        type: string
        description: Código do produto na plataforma.
      nome_produto:
        type: string
        description: Nome do produto.
      categoria:
        type: string
        description: Categoria do produto na plataforma.
      preco_original:
        type: number
        description: Preço original do produto.
      preco_promocional:
        type: number
        description: Preço promocional do produto.
      data_fim_promocao:
        type: string
        format: date-time
  produto_deleta_promocao:
    type: object
    properties:
      nome_produto:
        type: string
        description: Nome do produto em promocao
