swagger: '2.0'
info:
  title: API Lista Presentes
  description: API que contém os recursos para lista de presentes.
  version: '1.0.0'
host: localhost
basePath: /presentes/v1
tags:
  - name: tag-presentes
security:
  - client_id: []
  - access_token: []
securityDefinitions:
  client_id:
    type: apiKey
    in: header
    name: client_id
  access_token:
    type: apiKey
    in: header
    name: access_token
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /presentes:
    get:
      tags:
        - tag-presentes
      summary: Obtem uma lista de presentes
      description: Obtem produtos de um determinada lista de presentes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: presentes-query-param
          type: string
          description: Informar ID da lista de presentes.
          required: true
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: array
            items:
              $ref: '#/definitions/presentes'
        '400':
          description: ID da Lista de presentes não encontrado.
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
    post:
      tags:
        - tag-presentes
      summary: Incluir lista de presentes
      description: Realiza a inclusão de uma lista de presentes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: body
        name: body
        description: Corpo do request a ser enviado para inclusão da lista. Deve ser enviado uma lista com os IDs dos produtos a serem incluídos nela.
        required: true
        schema:
          $ref: '#/definitions/presente'
      security:
        - client_id: []
        - access_token: []
      responses:
        '201':
          description: Created.
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
    delete:
      tags:
        - tag-presentes
      summary: Exclui um lista de presentes
      description: Faz a exclusão de uma lista de presentes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: body
        name: body
        description: Corpo do request a ser enviado para exclusão da lista. A lista sera excluida contento itens na lista ou não.
        required: true
        schema:
          $ref: '#/definitions/presente'
      security:
        - client_id: []
        - access_token: []
      responses:
        '201':
          description: Deleted.
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.    
  /presentes/{IdProduto}:   
    put:
      tags:
        - tag-presentes
      summary: Atualiza dados de uma lista de presentes
      description: ''
      operationId: updatePresente
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: IdProduto
          in: path
          description: ID do produto na lista de presente
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Lista de presente precisa estar cadastrada previamente
          required: true
          schema:
            $ref: '#/definitions/presentePost'
      responses:
        '400':
          description: Identificador não válido
        '404':
          description: Produto não encontrado
        '405':
          description: Informações inválidas
    delete:
      tags:
        - tag-presentes
      summary: Deleta um produto de uma lista de presentes
      description: ''
      operationId: deletePresente
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: IdProduto
          in: path
          description: ID do produto na lista de presente
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Lista de presente precisa estar cadastrada previamente, o item deve compor a lista
          required: true
          schema:
            $ref: '#/definitions/presente'
      responses:
        '400':
          description: Identificador não válido
        '404':
          description: Produto não encontrado
        '405':
          description: Informações inválidas        
definitions:
  presentes:
    type: array
    items:
      type: object
      $ref: '#/definitions/presente'
  presente:
    type: object
    properties:
      idPresente:
        type: string
      produto:
        type: object
        $ref: '#/definitions/produtoPresente'
      embalagem:
        type: string
      fornecedores:
        type: array
        items:
          $ref: '#/definitions/fornecedor'
  produtoPresente:
    type: object
    properties:
      id:
        type: string
      nome:
        type: string
      preco:
        type: number
      avaliacoes:
        type: array
        items:
          $ref: '#/definitions/avaliacao'
  cliente:
    type: object
    properties:
      idCliente:
        type: string
      nota:
        type: number
      comentario:
        type: string
      idAvaliacao:
        type: string
  avaliacao:
    type: object
    properties:
      clientes:
        type: array
        items:
          type: object
          $ref: '#/definitions/cliente'
  fornecedor:
    type: object
    properties:
      idFornecedor:
        type: string
      name:
        type: string
      avaliacoes:
        type: object
        $ref: '#/definitions/avaliacao'
      mediaAvaliacao:
        type: number
      quantidadeVenda:
        type: integer
  presentePost:
    type: object
    properties:
      produtos:
        description: Informar os IDs dos produtos a serem incluídos na lista de presentes.
        type: array
        items:
          type: string
