swagger: '2.0'
info:
  description: "API que contém os recurosos para o e-Commerce Compra Fácil / Equipe 9."
  version: "1.0.0"
  title: "Compra Fácil API"
  termsOfService: "https://github.com/eNove/unicamp-engsoft-2020-inf332-pratica2"
  contact:
    email: "comprafacil@enove.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost
basePath: /presentes/v1
tags:
  - name: listadepresentes
security:
  - client_id: []
  - access_token: []
securityDefinitions:
  client_id:
    type: apiKey
    in: header
    name: client_id
  access_token:
    type: apiKey
    in: header
    name: access_token
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /presentes:
    post:
      tags:
        - listadepresentes
      summary: Oferecido para criar uma lista de presentes.
      description: Inclui uma lista de presentes para ser utilizada de acordo com a ocasião festiva.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: presente-query-param
          type: string
          description: Informar o SKU do produto.
          required: true
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: array
            items:
              $ref: '#/definitions/presente'
        '400':
          description: ID de produto inexistente.
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
    get:
      tags:
        - listadepresentes
      summary: "Lista de presentes"
      description: ""
      operationId: "listMaisVendidos"
      produces:
        - "application/json"
      parameters:
        - name: "_offset"
          in: header
          description: "Parâmetro que determina a posição inical da consulta."
          required: true
          type: "integer"
          format: "int64"
        - name: "_limit"
          in: header
          description: "Parâmetro que determina a quantidade de itens que serão retornados."
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: "Indica que o processamento foi bem sucedido."
          schema: 
              type: "array"
              items: 
                $ref: '#/definitions/presente'
        '403':
          description: "Requisição Inválida"
        '405':
          description: "Operação não permitida."
definitions:
  produto:
    type: object
    properties:
      id:
        type: string
      nome:
        type: string
      preco:
        type: number
      quantidadeTotal:
        type: number
      quantidadeLivre:
        type: number
      quantidadeBloqueada:
        type: number
  presente:
    type: object
    properties:
      idCliente:
        type: string
        description: Identificação do cliente.
      produtos:
        description: Lista dos produtos solicitados.
        type: array
        items:
          type: object
          $ref: '#/definitions/produto'
  cliente:
    type: object
    properties:
      idCliente:
        type: string
      nota:
        type: number
      comentario:
        type: string
      idAvaliacao:
        type: string
