swagger: '2.0'
info:
  description: "API contento os recurosos para o e-Commerce Compra Fácil / Grupo 9."
  version: "1.0.0"
  title: "Compra Fácil API"
  termsOfService: "https://github.com/eNove/unicamp-engsoft-2020-inf332-pratica2"
  contact:
    email: "comprafacil@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost
basePath: /precos/v1
tags:
  - name: tag-precos
  - name: promocao
security:
  - client_id: []
  - access_token: []
securityDefinitions:
  client_id:
    type: apiKey
    in: header
    name: client_id
  access_token:
    type: apiKey
    in: header
    name: access_token
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /comparar:
    get:
      tags:
        - tag-precos
      summary: Obtem coleção
      description: Obtem uma coleção de preços para o mesmo produto de fornecedores diferentes.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: precos-query-param
          type: string
          description: informar o SKU do produto
          required: true
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: array
            items:
              $ref: '#/definitions/precos'
        '400':
          description: Id de produto inexistênte.
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
  /promocoes:
    post:
      tags:
        - promocao
      summary: Obtem promocoes
      description: Obtem produtos em promocao no momento.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: "body"
        name: "body"
        description: "Promocoes de produtos do fornecedor"
        required: true
        schema:
          $ref: "#/definitions/promocao"
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: boolean
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
    get:
      tags:
        - promocao
      summary: Obtem promocoes
      description: Obtem produtos em promocao no momento.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: codigo_fornecedor
        in: query
        type: string
        description: "identificador do client de acesso"
        required: true
      - name: categoria
        in: query
        type: string
        description: Categoria do produto
        required: false
      - name: valormaximo
        in: query
        type: number
        description: Maior preco promocional aceitavel
        required: false 
      - name: produtos
        in: query
        type: array
        items:
          type: string
        description: Categoria do produto
        required: false
      security:
        - client_id: []
        - access_token: []
      responses:
        '200':
          description: Sucesso.
          schema:
            type: array
            items:
              $ref: '#/definitions/produto_promocao'
        '401':
          description: Não autorizado.
        '403':
          description: Proibido.
        '500':
          description: Erro Interno.
definitions:
  precos:
    type: object
    properties:
      idProduto:
        type: string
        description: Identificadro do produto.
      name:
        type: string
        description: Nome do produto.
      fornecedores:
        type: array
        description: lista de fornecedores do produto solicitado
        items:
            type: object
            $ref: '#/definitions/fornecedor'
  produto:
    type: object
    properties:
      id:
        type: string
      nome:
        type: string
      preco:
        type: number
      quantidadeTotal:
        type: number
      quantidadeLivre:
        type: number
      quantidadeBloqueada:
        type: number
  cliente:
    type: object
    properties:
      idCliente:
        type: string
      nota:
        type: number
      comentario:
        type: string
      idAvaliacao:
        type: string
  avaliacao:
    type: object
    properties:
      clientes:
        type: array
        items:
          type: object
          $ref: '#/definitions/cliente'
  fornecedor:
    type: object
    properties:
      idFornecedor:
        type: string
      name:
        type: string
      produtos:
        type: array
        items:
          type: object
          $ref: '#/definitions/produto'
      avaliacoes:
        type: object
        $ref: '#/definitions/avaliacao'
      mediaAvaliacao:
        type: number
      quantidadeVenda:
        type: integer
